import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import Header from "./header/Header";
import Footer from "./footer/Footer";
import "bootstrap/dist/css/bootstrap.min.css";
// import React from "react-bootstarap/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Agriculture Webflow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
